### PR TITLE
PR the napi work we did

### PR DESCRIPTION
**Pull request by bcomnes**
@chm-diederichs you did some more work too right?

### CODE REVIEW

**Comment by bcomnes** [comment]
Ok pulled it in.

**Comment by bompus** [comment]
Is it possible to release this? The latest Node is on abi=79 and if this is complete, it would make it easier for folks to upgrade without needing to remove + install to force the new node-gyp build, hoping it compiles.

**Comment by emilbayes** [comment]
@bompus yes but this only covers a tiny fraction of the api. We’re picking this work back up soon to get full parity with the current release

**Comment by mafintosh** [comment]
@chm-diederichs landed napi in master

**Pull request closed without merging**
