### PR TITLE
Feature/add chacha20 stream wrapper

### PR DESCRIPTION
**Pull request by ltjonka**
only salsa was supported before, so I added bindings for chacha

### CODE REVIEW

**Comment by mafintosh** [comment]
Code looks great! Could you add a note to the README?

Assuming @emilbayes says LGTM, I'm LGTM as well.

**Comment by ltjonka** [comment]
@mafintosh okay, I added the info to the readme

**Comment by mafintosh** [comment]
@emilbayes lgtm now?

**Comment by mafintosh** [comment]
wanna try out @juliangruber's new ci stuff when we prebuild this

**Comment by emilbayes** [comment]
Looks good now :) Out of curiosity, whats your usecase?

**Comment by ltjonka** [comment]
We are using it in an electron application for file encryption and signing. It is a good compromise between performance and maintainability.

**Comment by emilbayes** [comment]
Ahh ok. You do you own message authentication by some other means and use a KDF based nonce? Otherwise XSalsa is a good alternative :) And @mafintosh was able to get about 1.2GB/s throughput with that on one of the slower macbooks. Otherwise the AEAD primitives that sodium ships with are designed exactly for your use-case (encrypt and store some extra data, eg. app version)

**Comment by mafintosh** [comment]
out in 1.8.0

**Pull request merged**
