### PR TITLE
Add crypto_secretstream

### PR DESCRIPTION
**Pull request by emilbayes**
Two missing pieces:

* `crypto_secretstream_xchacha20poly1305_push` takes a `unsigned long long *clen_p` which allows you to read how many bytes were encrypted
* `crypto_secretstream_xchacha20poly1305_pull` has an analogous `unsigned long long *mlen_p`
* `crypto_secretstream_xchacha20poly1305_pull` also has a `unsigned char *tag_p` where it writes what the latest tag was

I'm not sure how we should expose these to javascript? Any (good) ideas?

/cc @mafintosh

### CODE REVIEW

**Comment by jedisct1** [comment]
`clen_p` and `mlen_p` can be convenient, but are not required at all. They were mainly added for consistency with the AEAD API, but it's fine to not expose them in wrappers, and just pass `NULL` as a pointer.

`tag_p` is required, though, if only to check that the end of the stream has been reached.

**Comment by jedisct1** [comment]
In the Swift and PHP APIs, `pull` returns a tuple (in PHP, an array) with the tag and the message.

**Comment by emilbayes** [comment]
@jedisct1 what is the rationale for tags being `unsigned char` rather than `uint32_t` or similar? Just trying to figure out how to best go about exposing :)

**Comment by jedisct1** [comment]
Minimizing overhead, since they are stored in every chunk. These are not supposed to be freely assignable values; each bit has a fixed meaning (and some have side effects, for example `_FINAL` does an implicit rekeying).

However, there are unused bits, that may be used for future extensions, including one that can indicate a variable-length tag.

**Comment by emilbayes** [comment]
@jedisct1 I have tried exposing `tag` and `clen` / `mlen` in a way that is in line with how the other apis are exposed, but I've had to so something I feel is quite dirty. I've exposed all the tags as Node.js Buffers, which allows one to compare byte by byte if two tags are the same. The issue, however, is that a Buffer is not resizable, so I need to know how big a tag is up front. What I've done is make a `crypto_secretstream_xchacha20poly1305_TAGBYTES_PATCH = 1U` const, but this is non-standard, and what I don't like. Do you have an idea of whether you'd be able to do something in libsodium that would help us out, while still keeping the API open for future changes?

**Comment by emilbayes** [comment]
@jedisct1 I see that you treat tags as a single byte in the swift bindings:

https://github.com/jedisct1/swift-sodium/blob/3a248f7ae359e399e549a93a43c46526203024f7/Sodium/SecretStream.swift#L11-L16

I think we will do the same here and export a `crypto_secretstream_xchacha20poly1305_TAGBYTES` constant for our users. If this changes in the future, it should be solved by a major bump :)

**Pull request merged**
