### PR TITLE
prebuild for arm

### PR DESCRIPTION
**Pull request by dominictarr**
I'm trying to get sodium-native working on linux-arm.
I did this, and it built on my laptop fine,
but on my arm device (rooted nexus 5 with arch linux running inside container)
it gave this error:

```
Error: /home/android/sodium-native/prebuilds/linux-arm/node-51.node: wrong ELF class: ELFCLASS64
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at load (/home/android/sodium-native/node_modules/node-gyp-build/index.js:13:10)
    at Object.<anonymous> (/home/android/sodium-native/index.js:1:101)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```

and when trying to build directly on the phone, it gave this python error:

```
...
make[2]: Leaving directory '/home/android/sodium-native/deps/libsodium'
make[1]: Leaving directory '/home/android/sodium-native/deps/libsodium'
Traceback (most recent call last):
  File "/home/android/.nvm/versions/node/v7.10.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 13, in <module>
    import gyp
  File "/home/android/.nvm/versions/node/v7.10.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 8, in <module>
    import gyp.input
  File "/home/android/.nvm/versions/node/v7.10.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 13, in <module>
    import gyp.common
  File "/home/android/.nvm/versions/node/v7.10.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/common.py", line 12, in <module>
    import tempfile
  File "/usr/lib/python2.7/tempfile.py", line 35, in <module>
    from random import Random as _Random
  File "/usr/lib/python2.7/random.py", line 885, in <module>
    _inst = Random()
  File "/usr/lib/python2.7/random.py", line 97, in __init__
    self.seed(x)
  File "/usr/lib/python2.7/random.py", line 113, in seed
    a = long(_hexlify(_urandom(2500)), 16)
OSError: [Errno 38] Function not implemented
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/android/.nvm/versions/node/v7.10.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:308:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexi
```

although, otherwise, the build looked good

### CODE REVIEW

**Comment by dominictarr** [comment]
am I missing something simple?

**Comment by mafintosh** [comment]
Can you normally cross compile to ARM on linux?

**Comment by dominictarr** [comment]
I think you can - but I also failed to compile directly from arm (the python error)

**Comment by dominictarr** [comment]
oh I know, ELFCLASS64 is the error you get when trying to run 64 bit binary on 32 system. 

```
>uname -a
Linux localhost 3.4.0-gd59db4e #1 SMP PREEMPT Mon Mar 17 15:16:36 PDT 2014 armv7l GNU/Linux
```

I'm on armv7, which is 32 bit!

**Comment by dominictarr** [comment]
hmm, according objdump on all my binaries (libsodium, node-51 and the node executable) it seems they are all 32 bit???

**Comment by mafintosh** [comment]
Try setting the arch explicitly to ia32.

**Comment by dominictarr** [comment]
that sounds like it wouldn't work, but I tried running that on the phone and got this:

```
> sodium-native@1.10.1 prebuild-ia32 /home/android/sodium-native
> prebuildify -a --strip --preinstall "node preinstall.js" --postinstall "node postinstall.js" --arch=ia32

checking build system type... armv7l-unknown-linux-gnueabihf
checking host system type... armv7l-unknown-linux-gnueabihf
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '1000' is supported by ustar format... yes
checking whether GID '1000' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/home/android/sodium-native/deps/libsodium':
configure: error: C compiler cannot create executables
See `config.log' for more details
/home/android/sodium-native/preinstall.js:91
    if (err) throw err
             ^

Error: ./configure exited with 77
    at ChildProcess.<anonymous> (/home/android/sodium-native/preinstall.js:131:25)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

**Comment by dominictarr** [comment]
aha, my problem is this:

https://docs.python.org/2/library/os.html#miscellaneous-functions

hmm...

https://serverfault.com/questions/848552/can-not-import-random-with-python2

**Comment by dominictarr** [comment]
this rabbit hole is getting a bit deep, I'm just gonna try debian on the phone instead of arch...

**Comment by mafintosh** [comment]
@dominictarr do you need 32bit or 64bit arm for the phone? I have a raspberry pie lying around somewhere ...

**Comment by dominictarr** [comment]
Okay, it worked this time! running node 7 on ubuntu on linux, (that weird thing was just arch on arm being difficult) any it works now it just takes ages - what do we need to get arm prebuilds up?

**Comment by mafintosh** [comment]
If you can share how you build the arm build on linux I'll add the prebuild
:)

/m

**Comment by dominictarr** [comment]
I built this on the phone, but I'll try building it from linux, there are some vps that run on arm these days, prehaps that is an option?

**Comment by mafintosh** [comment]
@dominictarr do you know if the phone is using arm hard float? i wanna try rebuilding from x64 using this https://www.acmesystems.it/arm9_toolchain

**Comment by dominictarr** [comment]
it's an armv71 https://android.stackexchange.com/questions/116658/does-google-nexus-5-has-arm-or-armx86-or-armx64-processor

**Comment by mafintosh** [comment]
@dominictarr try latest sodium-native - it has prebuilds for arm i built on a pi3b

**Comment by mafintosh** [comment]
this is fixed

**Pull request closed without merging**
