### PR TITLE
Pointer trick

### PR DESCRIPTION
**Pull request by emilbayes**

### CODE REVIEW

**Comment by emilbayes** [comment]
Only missing crypt_hash now and update `sodium-test` (and consequently `sodium-javascript`)

**Comment by cakoose** [comment]
It looks like this doesn't handle alignment issues.  (Or perhaps I'm misunderstanding something?)

The sha256 and sha512 state structs have `uint64_t` components, which means they must be 8-byte aligned.  Freshly-allocated `Buffer`s seem to be 8-byte aligned ([code](https://github.com/nodejs/node/blob/eef6504cf7b95ada170ec9878089ce57fde551d8/lib/buffer.js#L122)), but I'm not sure if that's guaranteed by the Node API or just an implementation detail that may change in the future.

Either way, you can still get non-8-byte aligned buffers with `Buffer.slice()`.  Incorrect alignment is "undefined behavior" in C, which is dangerous territory.

The blake2b state struct is intended to be 64-byte aligned: [code](https://github.com/jedisct1/libsodium/blob/b42082d6d265d17fd6116b7fc7b1f1363bbab32f/src/libsodium/include/sodium/crypto_generichash_blake2b.h#L23).  The "sodium" NPM module makes sure to respect the alignment: [code](https://github.com/paixaop/node-sodium/blob/511731428519cc0eca770db7046e5131994fa57d/src/crypto_generichash_blake2b.cc#L67).

If this actually is a problem:
1. Functions that accept a state buffer should check that the buffer is correctly aligned.
2. Maybe we should provide functions to allocate state buffers that are correctly aligned?
3. Maybe we should expose the alignment requirements so callers can align things themselves?

**Comment by emilbayes** [comment]
@cakoose Good point! Some more questions:

How does the linked code ensure alignment? `crypto_generichash_blake2b_statebytes()` is simply returning a constant which is already rounded off to nearest 64 bytes ([source](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_generichash/crypto_generichash.c#L48-L51)), which the node-sodium then rounds off again (maybe due to legacy). I think they have the same issue as us, but maybe I'm missing something :) 

How the passed buffer is aligned is up to the user to ensure and we should probably have big warnings about it, (we were aware of it, but not sure how to ensure this. Eg the one-time auth docs mention alignment as required: https://download.libsodium.org/doc/advanced/poly1305). I don't even think it's possible without your own native code to check this. To ensure at least memory page alignment, Buffer.allocSlow or our sodium.sodium_malloc would need to be used, but they have downsides (due to different goals) that make the allocations way slower than Buffer.alloc. What would you suggest? Here's a couple of ideas off the top of my head:
* That we expose a separate method to inspect the pointer of a Buffer and then you can adjust the alignment (eg. by always allocating an extra 63 bytes if you need 64 byte alignment). 
* Use asserts in the init methods like we have now for other checks. 
* Expose something like `Buffer.allocSlow` which takes an extra alignment parameter.

The next question is how to extract the alignment information, as this is not exposed anywhere, except though compiler attributes. Also looking at the gcc docs, it mentions that maximum alignment for a lot of linkers is very small, while some of the libsodium structs have very large alignment (eg. 64 bytes for blake2b). Do you know any more about this? If not we may be lucky to summon Frank Denis who wrote libsodium :)

**EDIT** Missed the bullet points at the end of your comment. Node Buffers uses Pool allocator to make allocations fast. So I don't think you can ever have any guarantees about the alignment of the Buffers (unless we convince them to make the 8 byte alignment a guarantee). So it seems we were thinking the same things, however I do have some open questions regarding how we make this fast. You must have the same, seeing your initial issue was motivated by performance.

**Comment by cakoose** [comment]
> How does the linked code ensure alignment?

Oh, you're right!  I didn't read the code carefully.

It seems like that code should actually be:

```c
NEW_BUFFER_AND_PTR(state, crypto_generichash_blake2b_statebytes() + 63);
uintptr_t state_ptr_int = (uintptr_t) state_ptr;
state_ptr_int = (state_ptr_int + 63) & ~(uintptr_t) 63;
state_ptr = (unsigned char*) state_ptr_int;
```

> `crypto_generichash_blake2b_statebytes()` is simply returning a constant which is already rounded off to nearest 64 bytes ([source](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_generichash/crypto_generichash.c#L48-L51))

That's interesting.  I _think_ the `CRYPTO_ALIGN(64)` is enough to cause the `sizeof(...)` to be rounded up to the nearest 64 bytes.  Not sure why they also manually rounded it up.

BTW, here's a libsodium issue that discusses alignment problems: <https://github.com/jedisct1/libsodium/issues/651>.  There it says "64-bytes alignment is recommended for performance, but not required".  However, the latest libsodium docs for crypto_generichash say "64-bytes alignment is required": [link](https://libsodium.gitbook.io/doc/hashing/generic_hashing#state-structure-size).

> The next question is how to extract the alignment information, as this is not exposed anywhere, except though compiler attributes.

In C you'd use the `offsetof` trick.  But C++ has the `alignof` operator that does it all for you.  Quick demo: https://gist.github.com/cakoose/52f9ea60070d0bb91bb9f2bbd41ba57f

**API questions**

If the user passes in an unaligned buffer, we have a couple options:
1. Reject it.
2. If there is enough space at the end, adjust the pointer forward to an aligned address and use it.  If there isn't enough space at the end, reject it.  (This is what my demo code above does.)

Option 1 is my personal preference.  It's less magical.  It's also slightly faster.

We can provide a helper function `crypto_generichash_alloc_state_buffer` that returns a Node `Buffer` with the correct alignment.  (Simple implementation that wastes some space: alloc a buffer with spare room at the end, adjust the pointer forward to an aligned boundary.)

And if people want to allocate an array of state buffers at once, we could provide `crypto_generichash_alloc_state_buffer_array`.  The advantage is that we can allocate N state buffers in contiguous memory with just one wasted "alignment gap".  (No need to do this for the initial implementation, obviously...)

**Avoid `Buffer` entirely?**

All that said, casting pointers like this seems dangerous.  I don't understand this stuff very well, but I wonder if it might be violating the strict aliasing rule (https://stackoverflow.com/a/99010).

Another option is to just keep doing the `Nan:ObjectWrap` thing, except without instance methods.
- `crypto_generichash_alloc` would return a heap-allocated instance.  (Unlike `malloc`, C++ `new` is type-aware, so I think it will respect alignment.)
- Instead of instance methods, have two functions: `crypto_generichash_update` and `crypto_generichash_final`
- Those two functions just have to do a quick(?) instanceof check of their `state` parameter and then use the struct directly.

**Comment by cakoose** [comment]
Also, just saw this: https://github.com/bobrik/node-aligned-buffer/blob/master/src/aligned-buffer.cc

Is this what you meant by `Buffer.allocSlow`?

**Comment by emilbayes** [comment]
Saw that project, but was last updated in 2012 and lot's have happened to Buffers since then :)
I was thinking of this API: https://nodejs.org/api/buffer.html#buffer_class_method_buffer_allocunsafeslow_size

**Comment by cakoose** [comment]
Looked into the strict aliasing rule a bit more and found out it's ok to read/write other data via a `char*` or `unsigned char*` -- somewhat obvious in retrospect, otherwise `memcpy` wouldn't work!

So the option of providing an allocation function that returns a `Buffer` should work.

**Some open questions**

How should `crypto_generichash_alloc_state()` allocate?
- Node buffer pool
    - Con: Need to allocate 63 extra bytes to guarantee alignment.  (Only 7 extra bytes for SHA-2.)
- C++ `new` wrapped in [`napi_create_external_buffer`](https://nodejs.org/api/n-api.html#n_api_napi_create_external_buffer)
    - Pro: Can allocate exactly as much as we need.
    - Con: Maybe slower than the Node buffer pool? 
- C++ `new` wrapped in [`napi_create_external`](https://nodejs.org/api/n-api.html#n_api_napi_create_external)
    - Con: JS code can't access raw bytes directly (e.g. for serializing somewhere).
    - Pro: With `Buffer`, users might think they can pass any buffer in -- which might work during development but then fail in production.  With a custom object, maybe we can do stricter checks to ensure it was definitely allocated via `crypto_generichash_alloc_state()`?

Should `crypto_generichash_alloc_state()` initialize the state?
- Yes?
    - Pro: Harder to make mistakes.
    - To reuse an allocated state, we could provide `crypto_generichash_reset()`.
- No -- have a separate `crypto_generichash_init()`
    - Pro: Closer to libsodium API.
    - Pro: When allocating state for copying/deserializing state, it's wasteful to initialize it since we're immediately going to overwrite it.

**Comment by emilbayes** [comment]
Goal #1 of this module is to stay as close to the C API as possible, even if that means doing something that's not very "javascripty" or which requires extra care of the developer. So I think what I'd like to do is warn users about the pitfalls of unaligned memory, write extensive tests with misalignment we can run, and have an assert to check alignment of the passed buffer. Allocating the extra memory for alignment is not that big of an issue in my book, it's only 63 bytes of padding, which is pretty minimal in the overall scheme of things. And since all the relevant APIs will be sync, people can reuse the buffers as they please (we do this in a lot of our applications).

**Comment by cakoose** [comment]
Just to be clear, are you saying you want to provide a `crypto_generichash_alloc_state()` function that allocates from the Node `Buffer` pool and adjusts the starting pointer to be aligned?

BTW, I appreciate the goal of being close to the C API.  And so I think it makes sense to have an explicit `crypto_generichash_init()`.  But for `crypto_generichash_alloc_state()` there is no C API to follow!  I think C users typically keep `crypto_generichash_state` on the stack.  And if they heap-allocate with `malloc` they're in trouble because `malloc` isn't type-aware so the alignment won't be correct.

**Comment by emilbayes** [comment]
Hey @jedisct1, we're due for a major rewrite of the bindings to the new N-API in Node, since the Nan stuff is not something we want to stick with, and we're now getting too many deprecations. We would like to introduce this trick also to get rid of the C++ wrapper classes for stateful functions.

Can you comment on the alignment of `crypto_onetimeauth_state` and `crypto_generichash_state`? Since we cannot guarantee alignment when allocating Buffers in Node.js (however an implementation detail is that they are multiples of 8), should we do the trick where we alloc up to `sizeof(state) - 1` extra space and fix alignment in C land at the expense of some wasted memory? What are the consequences of misalignment? I assume that `sodium_malloc` will give the correct alignment since a page size should be a higher power of two and hence is divisible by the state sizes?

**Comment by jedisct1** [comment]
Hi Emil,

The only implication of not having  the correct alignment will be a speed penalty, which is negligible on modern CPUs.

**Comment by emilbayes** [comment]
@jedisct1 Thanks! We will take the penalty. We can always expose a helper to do opt-in alignment

**Comment by cakoose** [comment]
@jedisct1: Interesting to learn that unaligned access on Intel is fast now.  (Your comment prompted me to dig a little and I found this: https://lemire.me/blog/2012/05/31/data-alignment-for-speed-myth-or-reality/#comment-55271)

I was under the impression that an unaligned read was considered "undefined behavior" in C, which seems like dangerous territory.  Is that not the case?

Also, do people care about ARM processors?  It looks like Node and libsodium are supported on both.  I remember using C++ on ARM a long time ago and finding out that unaligned access was not supported.

**Comment by jedisct1** [comment]
Unaligned reads can cause a trap. A 4 byes alignment will prevent it on all architectures I'm aware of. @emilbayes pointed out that `Buffers` had a 8 bytes alignment.

ARM CPUs support unaligned accesses since ARMv6.

This applies to general-purpose registers, not to vector registers. For these, aligned and unaligned accesses use different opcodes.

The former used to be faster, but would immediately trap if an unaligned address was accessed.

The later used to be slower. On ARM, it was using software emulation. On Intel, it was slow because the CPU couldn't predict that concurrent opcodes would not overlap.

Libsodium now uses the opcodes for unaligned accesses everywhere. This adds a performance penalty on older CPUs, but greatly improves usability, while not having a significant impact on the vast majority of CPUs.

**Comment by cakoose** [comment]
@jedisct1: Thanks!  To make sure I understand, are the following two statements true:
1. If we pass libsodium a 4-byte aligned buffer, everything will work correctly.
2. If we pass libsodium a non-4-byte aligned buffer, it will trap.  Importantly, it will _not_ produce incorrect output and return normally.

@emilbayes: Node's `Buffer.alloc` currently returns 8-byte aligned addresses, but people might use `Buffer.slice()` to get an arbitrary subsegment of that buffer.  Just for user-friendliness, if we accept user-supplied `Buffers`, it might be a good idea to do a quick 4-byte alignment check before passing it to `libsodium`.

**Comment by jedisct1** [comment]
If you expect people to run Node on ARMv5 or older, adding that check may be a good idea.
Or else, yes, an unaligned access will trap.

**Comment by emilbayes** [comment]
We officially support ARM7. What platforms use ARM5? Old RPi's?

**Comment by jedisct1** [comment]
Even the RPi v1 has an ARMv6.

**Comment by cakoose** [comment]
Even if we're guaranteed to trap, I think it's useful to have an explicit check that raises an exception with a friendly error message, e.g. "buffer's start address is not a multiple of 4".

Not sure how Node handles traps.  If it just abruptly kills the process, that's kind of rough.  It doesn't give the program a chance to log the error or clean up after itself.

If Node converts traps to JS exceptions, that's great.  But I'm guessing the exception message will be somewhat difficult for users to understand.

An explicit check is very cheap, so it seems worth it.  (Just stating my opinion because this stuff is interesting to me.  I don't mean to tell you how to run your project, so obviously feel free to ignore all this if you prefer!)

**Pull request closed without merging**
