### PR TITLE
Ristretto bindings

### PR DESCRIPTION
**Pull request by lukeburns**
Added ristretto255 bindings + ported tests and example from libsodium

### CODE REVIEW

**Comment by chm-diederichs** [comment]
Thanks for doing the work on this PR @lukeburns! Going to test it some more and then merge soon, hopefully.

**Comment by lukeburns** [comment]
Also see https://github.com/sodium-friends/sodium-javascript/pull/63

**Review by hamzalhammadi — COMMENTED** [review]
ا

**Review by hamzalhammadi — APPROVED** [review]

**Comment by mafintosh** [comment]
Closing for now as this has been open forever, feel free to reopen if still relevant

**Pull request closed without merging**
